export const products = [
    {
      "id": "Buy4meoa",
      "name": "Apple iPhone 14 Pro Max",
      "company": "Apple",
      "price": 7499900,
      "colors": ["#ff0000", "#000000", "#CDD0D0"],
      "star":"5",
      "img1": "https://cellbuddy.in/buddy/wp-content/uploads/2022/09/14-Pro-Gold.png",
      "img2":"https://cellbuddy.in/buddy/wp-content/uploads/2022/09/14-Pro-Gold-3-768x768.png",
      "img3":"https://cellbuddy.in/buddy/wp-content/uploads/2022/09/12-Pro-Max-Graphite-3.png",
    
      "description": "The iPhone X features a 5.8-inch OLED display, a powerful A11 Bionic chip, and a 12MP dual camera system with enhanced capabilities for low-light photography. It's designed for a premium feel with a sleek, all-glass body.",
      "category": "mobile",
      "featured": true
    },
    {
      "id": "Buy4meob",
      "name": "Samsung S20",
      "company": "Samsung",
      "star":"4.5",
      "price": 5000000,
      "colors": ["#000000", "#22D3EF"],
      "img1": "https://images.pexels.com/photos/404280/pexels-photo-404280.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      "description": "The Samsung S20 offers a 6.2-inch AMOLED screen, a versatile triple camera setup with 64MP telephoto lens, and powerful Exynos 990 or Snapdragon 865 processor. It's designed for an immersive experience and high performance.",
      "category": "mobile",
      "shipping": true
    },
    {
      "id": "Buy4meoc",
      "name": "Dell Series",
      "star":"4.5",
      "company": "Dell",
      "price": 600000,
      "colors": ["#22D3EF", "#CDD0D0"],
      "img1": "https://images.pexels.com/photos/7974/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      "description": "The Dell Series laptops offer high performance with Intel or AMD processors, sleek designs, and a range of display options. Ideal for both professional and personal use.",
      "category": "laptop"
    },
    {
      "id": "Buy4meod",
      "name": "Nokia 420",
      "company": "Nokia",
      "star":"4.5",
      "price": 12599,
      "colors": ["#000000", "#CDD0D0"],
      "img1": "https://images.pexels.com/photos/4224099/pexels-photo-4224099.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      "description": "The Nokia 420 is a budget-friendly phone with a durable build and a focus on essential features. It provides a reliable performance for everyday tasks.",
      "category": "mobile",
      "shipping": true
    },
    {
      "id": "Buy4meoe",
      "name": "Mac PC",
      "company": "Apple",
      "price": 4000099,
      "colors": ["#000000", "#CDD0D0"],
      "img1": "https://images.pexels.com/photos/1029757/pexels-photo-1029757.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      "description": "The Mac PC features a high-resolution display, a powerful M1 chip, and a sleek design. It's optimized for creative professionals and offers seamless integration with Apple's ecosystem.",
      "category": "computer",
      "shipping": true
    },
    {
      "id": "Buy4meof",
      "name": "MacBook Pro",
      "company": "Apple",
      "star":"3.5",
      "price": 42999,
      "colors": ["#000000", "#CDD0D0"],
      "img1": "https://images.pexels.com/photos/303383/pexels-photo-303383.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      "description": "The MacBook Pro is known for its powerful performance with Intel or M1 chips, a stunning Retina display, and exceptional build quality. It's perfect for professionals and creatives.",
      "category": "laptop",
      "shipping": true
    },
    {
      "id": "Buy4meog",
      "name": "Asus G Series",
      "company": "Asus",
      "price": 23999,
      "star":"4.5",
      "colors": ["#CDD0D0", "#000000"],
      "img1": "https://images.pexels.com/photos/261662/pexels-photo-261662.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      "description": "The Asus G Series laptops are designed for gamers, featuring high-performance processors, advanced cooling systems, and vibrant displays. They're built for intensive gaming sessions and multimedia tasks.",
      "category": "laptop",
      "shipping": true
    },
    {
      "id": "Buy4meoh",
      "name": "Apple AirPods Pro",
      "company": "Apple",
      "star":"4.5",
      "price": 1699900,
      "colors": ["#000000", "#CDD0D0"],
      "img1": "https://cellbuddy.in/buddy/wp-content/uploads/2022/10/airpodspro2-01.png",
      "img2":"https://cellbuddy.in/buddy/wp-content/uploads/2022/10/airpodspro2-03.png",
      "img3":"https://cellbuddy.in/buddy/wp-content/uploads/2022/10/airpodspro2-02.png",
      "description": "Additional Features: Here comes the all new and updated version of Apple Airpods Pro with Charging Case that crafts itself with design and capabilities which will make your hearing experience rise to a boost",
      "category": " AirPods",
      "featured": true,
      "shipping": true
    },
    {
      "id": "Buy4meoi",
      "name": "Apple Watch",
      "company": "Apple",
      "price": 39999,
      "colors": ["#000000"],
      "img1": "https://images.pexels.com/photos/437037/pexels-photo-437037.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      "description": "The Apple Watch combines a sleek design with advanced health and fitness tracking features. It includes notifications, GPS, and integration with Apple's ecosystem.",
      "category": "watch",
      "shipping": true
    },
    {
      "id": "Buy4meoj",
      "name": "User Need",
      "company": "Apple",
      "star":"4.5",
      "price": 300099,
      "colors": ["#ff0000", "#22D3EF", "#000000"],
      "img1": "https://images.pexels.com/photos/1619651/pexels-photo-1619651.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      "description": "A customized product tailored to user needs with premium features and high-quality materials. Ideal for those seeking a unique and high-end experience.",
      "category": "accessories"
    },
    {
      "id": "Buy4meok",
      "name": "Rolex Premium",
      "company": "Rolex",
      "star":"4.5",
      "price": 999999,
      "colors": ["#000000", "#CDD0D0"],
     "img1": "https://images.pexels.com/photos/1697214/pexels-photo-1697214.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      "description": "The Rolex Premium watch features a sophisticated design, precision craftsmanship, and luxurious materials. It's a symbol of status and quality.",
      "category": "watch"
    },
    {
      "id": "Buy4meol",
      "name": "Galaxy W20",
      "star":"4.5",
      "company": "Samsung",
      "price": 2299900,
      "colors": ["#22D3EF", "#ff0000", "#000000"],
      "img1": "https://cellbuddy.in/buddy/wp-content/uploads/2022/09/Series-7-41-_-45mm-GPSCellular-Red.png",
      "img2":"https://cellbuddy.in/buddy/wp-content/uploads/2022/09/Series-7-41-_-45mm-GPSCellular-Gold-2.png",
      "img3":"https://cellbuddy.in/buddy/wp-content/uploads/2022/09/Series-7-41-_-45mm-GPSCellular-Starlight-2.png",
      "description": "The largest, most advanced Always-on Retina display yet makes everything you do with your Apple Watch Series 7 bigger and better. Series 7 is the most durable Apple Watch ever built, with an even more crack-resistant front crystal.",
      "category": "watch",
      "featured": true
    }
  ];
  